---
# handlers file for node-exporter
- name: reload systemd 
  ansible.builtin.systemd:
    daemon_reload: yes

- name: start node_exporter
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    name: node_exporter
   