---
# handlers file for node-exporter
- name: Reload do systemd 
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start node_exporter
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    name: node_exporter
   