---
# tasks para a instalação do node-exporter

- name: Download e descompactando o node-exporter
  ansible.builtin.unarchive:
    src: "{{ url_node_exporter}}"
    dest: /tmp
    remote_src: yes

- name: Verificar se folder node_exporter existe
  stat:
    path: /usr/bin/node_exporter
  register: register_name

- name: Copiando arquivos do node-exporter se nao existir o diretorio
  ansible.builtin.shell:
    cmd: cp -v "{{ node_exporter_version }}"/node_exporter /usr/bin
    chdir: /tmp
  when: not register_name.stat.exists
  
- name: criar usuário node-exporter
  ansible.builtin.user:
    name: node_exporter
    shell: /sbin/nologin
    create_home: False

- name: copiando node_exporter.service e executando servico
  ansible.builtin.copy:
    src: node_exporter.service 
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root 
    mode: "755"
    notify:
      - Reload do systemd 
      - Start node_exporter

